### ISSUE TITLE
Redstone mod

### ISSUE THREAD

**Issue by em1tter** [4dMinerCommunity/.github#2]
Things like basic redstone things and pistons and so. Thanks.

**Comment by ghost** [comment]
this is for adding made mods...
you can lurk around til we can add blocks, then someone will prob add it

**Comment by em1tter** [comment]
> this is for adding made mods... you can lurk around til we can add blocks, then someone will prob add it

Sorry, I understanded it wrongly.

**Comment by ghost** [comment]
Thats fine, il edit the gh org readme to say that
